use_frameworks!
platform :ios, '9.0'
source 'git@github.com:rushairer/iOSSpec.git'

target 'ARObjectCollectionViewController_Tests' do
  pod 'ARObjectCollectionViewController', :path => '../'
  
  
end
